# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtoconfXds < Formula
  desc "Envoy XDS integration for protoconf"
  homepage "https://docs.protoconf.sh/"
  version "0.1.2-2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/protoconf/protoconf-xds/releases/download/v0.1.2-2/protoconf-xds_0.1.2-2_darwin_amd64.tar.gz"
      sha256 "e4cc21fa2eb25ca84a837e860b3f9255f18f823d774823a436394d350949cc12"

      def install
        bin.install "protoconf-xds"
      end
    end
    on_arm do
      url "https://github.com/protoconf/protoconf-xds/releases/download/v0.1.2-2/protoconf-xds_0.1.2-2_darwin_arm64.tar.gz"
      sha256 "bd05f09fa50117a85579301eff6e0826d1f1f4b7463a3addfd4489e1289bbd37"

      def install
        bin.install "protoconf-xds"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/protoconf/protoconf-xds/releases/download/v0.1.2-2/protoconf-xds_0.1.2-2_linux_amd64.tar.gz"
        sha256 "3d5ef61c084cf4cc2b4f27695659d87482d2312c7ca46a4770f499a2f0cec071"

        def install
          bin.install "protoconf-xds"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/protoconf/protoconf-xds/releases/download/v0.1.2-2/protoconf-xds_0.1.2-2_linux_arm64.tar.gz"
        sha256 "ba250d67253209e61b6ec40ccddbc7e5830f3b9f4cb7d35ed773be118b6dce74"

        def install
          bin.install "protoconf-xds"
        end
      end
    end
  end
end
