# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protoconf < Formula
  desc "Configuration as Code framework based on protobuf and Starlark."
  homepage "https://www.protoconf.dev/"
  version "0.2.0-alpha2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/protoconf/protoconf/releases/download/v0.2.0-alpha2/protoconf_0.2.0-alpha2_darwin_amd64.tar.gz"
      sha256 "04d0fc68e7dd9226aa52f97ee9ea477378b67214b3f8c163f97f79cdc5ef0145"

      def install
        bin.install "protoconf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/protoconf/protoconf/releases/download/v0.2.0-alpha2/protoconf_0.2.0-alpha2_darwin_arm64.tar.gz"
      sha256 "9306d23f7819dc1ebdb880e590c7e7a0eca33182e55524eee09845b0acdb8279"

      def install
        bin.install "protoconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/protoconf/protoconf/releases/download/v0.2.0-alpha2/protoconf_0.2.0-alpha2_linux_amd64.tar.gz"
        sha256 "fd40daeffd08a6039fd48dfff6776333204005d8bdc468b00aa57dc50955a934"

        def install
          bin.install "protoconf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/protoconf/protoconf/releases/download/v0.2.0-alpha2/protoconf_0.2.0-alpha2_linux_arm64.tar.gz"
        sha256 "9727d784d2a40a46e43075b27d8afb27b174a8e9f7a0ddab14106adcb9c13f2d"

        def install
          bin.install "protoconf"
        end
      end
    end
  end
end
