# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtoconfTerraform < Formula
  desc "Terraform integration for protoconf"
  homepage "https://docs.protoconf.sh/"
  version "0.1.4-4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/protoconf/protoconf-terraform/releases/download/v0.1.4-4/protoconf-terraform_0.1.4-4_darwin_arm64.tar.gz"
      sha256 "2b0df652f128328a5c64a1072b7eda2afcdb8ca1b982b9a35a13611fe06405dc"

      def install
        bin.install "protoconf-terraform"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoconf/protoconf-terraform/releases/download/v0.1.4-4/protoconf-terraform_0.1.4-4_darwin_amd64.tar.gz"
      sha256 "5040b4763081085b9f4e8a31b6f0a9c1ab191a201f0d484ebac5e043e6038938"

      def install
        bin.install "protoconf-terraform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/protoconf/protoconf-terraform/releases/download/v0.1.4-4/protoconf-terraform_0.1.4-4_linux_amd64.tar.gz"
      sha256 "14fd82d94945bd09aadb26640d9f56f1ce9279c4c31190e21f79bff4b13baa42"

      def install
        bin.install "protoconf-terraform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/protoconf/protoconf-terraform/releases/download/v0.1.4-4/protoconf-terraform_0.1.4-4_linux_arm64.tar.gz"
      sha256 "3a54d453d8d14746067c9b1b38ac316d2ffe63edee1ee610b585421a71c49824"

      def install
        bin.install "protoconf-terraform"
      end
    end
  end
end
