# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protoconf < Formula
  desc "Configuration as Code framework based on protobuf and Starlark."
  homepage "https://docs.protoconf.sh/"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/protoconf/protoconf/releases/download/v0.1.6/protoconf_0.1.6_darwin_arm64.tar.gz"
      sha256 "700fd2e7151156675de42ee84686fbcc407faa6916266577337fd255f201ca30"

      def install
        bin.install "protoconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoconf/protoconf/releases/download/v0.1.6/protoconf_0.1.6_darwin_amd64.tar.gz"
      sha256 "43f32b348b9c43190a1f5fe794997dc3ccee7f27ac3776813e3616549a32f1be"

      def install
        bin.install "protoconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/protoconf/protoconf/releases/download/v0.1.6/protoconf_0.1.6_linux_arm64.tar.gz"
      sha256 "0e6689210696d27e81ed1cea440e41144d1428e3d0e1a1bfd513984f01f12ad1"

      def install
        bin.install "protoconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoconf/protoconf/releases/download/v0.1.6/protoconf_0.1.6_linux_amd64.tar.gz"
      sha256 "2018ba15152cab605cc88c375a292a7a9bc3116647e62b7d745b3c642743fef2"

      def install
        bin.install "protoconf"
      end
    end
  end
end
