# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Protoconf < Formula
  desc "Configuration as Code framework based on protobuf and Starlark."
  homepage "https://www.protoconf.dev/"
  version "0.2.0-alpha1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/protoconf/protoconf/releases/download/v0.2.0-alpha1/protoconf_0.2.0-alpha1_darwin_amd64.tar.gz"
      sha256 "e281ffaf6911893038ed2b9e95d9f950de49bdf014f1c91177781aadb59ee9ba"

      def install
        bin.install "protoconf"
      end
    end
    on_arm do
      url "https://github.com/protoconf/protoconf/releases/download/v0.2.0-alpha1/protoconf_0.2.0-alpha1_darwin_arm64.tar.gz"
      sha256 "219f403e7d4c0aa5b90d04b33db859bf65cbf2f6a2f0a44ff0d6d8f87cb89f41"

      def install
        bin.install "protoconf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/protoconf/protoconf/releases/download/v0.2.0-alpha1/protoconf_0.2.0-alpha1_linux_amd64.tar.gz"
        sha256 "337f467205e3e5c6b9c457d0c14281a9f3b51ab486ab6cde6f173df87bf7333b"

        def install
          bin.install "protoconf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/protoconf/protoconf/releases/download/v0.2.0-alpha1/protoconf_0.2.0-alpha1_linux_arm64.tar.gz"
        sha256 "d376b8cc53e8ac8a4555f493297347b66e42c4b9d2cd93ce992a99d2682675dc"

        def install
          bin.install "protoconf"
        end
      end
    end
  end
end
