# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtoconfXds < Formula
  desc "Envoy XDS integration for protoconf"
  homepage "https://docs.protoconf.sh/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/protoconf/protoconf-xds/releases/download/v0.1.0/protoconf-xds_0.1.0_darwin_amd64.tar.gz"
      sha256 "43f03ed8aaf770e2f36f1c586ffcaaaa8d649e88ea17d88b76491cd8490c8bdd"

      def install
        bin.install "protoconf-xds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/protoconf/protoconf-xds/releases/download/v0.1.0/protoconf-xds_0.1.0_darwin_arm64.tar.gz"
      sha256 "1b8d4116c78134b2209ccf2c0889716250bff012f08982def57ae0c231253575"

      def install
        bin.install "protoconf-xds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/protoconf/protoconf-xds/releases/download/v0.1.0/protoconf-xds_0.1.0_linux_arm64.tar.gz"
      sha256 "9d752e6e42317d92680a7a09d6c171f546cabd8b09fdb36ff1628223b662a588"

      def install
        bin.install "protoconf-xds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/protoconf/protoconf-xds/releases/download/v0.1.0/protoconf-xds_0.1.0_linux_amd64.tar.gz"
      sha256 "cd81e45dcc0af99f723351473fe9253f1c699891a40880e5be8d88cbe2a194b1"

      def install
        bin.install "protoconf-xds"
      end
    end
  end
end
